# Generated by Django 5.2 on 2025-04-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='CameraLogs',
            fields=[
                ('camera_id', models.IntegerField(primary_key=True, serialize=False)),
                ('flood_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorCamera',
            fields=[
                ('pair_id', models.IntegerField(primary_key=True, serialize=False)),
                ('current_depth', models.FloatField()),
                ('location', models.TextField()),
                ('flood_number', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorLogs',
            fields=[
                ('sensor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('depth', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('flood_number', models.IntegerField()),
            ],
        ),
    ]
