# Generated by Django 5.2 on 2025-04-25 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cameralogs',
            name='camera_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensorcamera'),
        ),
        migrations.AlterField(
            model_name='sensorlogs',
            name='sensor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sensorcamera'),
        ),
        migrations.AddField(
            model_name='cameralogs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='sensorlogs',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
