# Generated by Django 5.2 on 2025-04-25 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0002_cameralogs_id_sensorlogs_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorcamera',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
