# Generated by Django 5.2 on 2025-04-25 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0003_alter_sensorcamera_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcamera',
            name='threshold_depth',
            field=models.FloatField(default=0.5),
        ),
    ]
