# Generated by Django 5.2 on 2025-04-26 20:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sensorcamera_threshold_depth'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameralogs',
            name='image',
            field=models.ImageField(default=None, storage=core.models.CameraImageStorage, upload_to=''),
            preserve_default=False,
        ),
    ]
