# Generated by Django 5.2 on 2025-04-29 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_sensorcamera_current_depth_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcamera',
            name='pair_name',
            field=models.CharField(default=''),
            preserve_default=False,
        ),
    ]
