# Generated by Django 5.2 on 2025-04-30 01:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0007_sensorcamera_pair_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcamera',
            name='monitor_state',
            field=models.CharField(
                choices=[
                    ('Dangerous', 'Dangerous'),
                    ('Caution', 'Caution'),
                    ('Safe', 'Safe'),
                    ('Unresponsive', 'Unresponsive'),
                ],
                default='Unresponsive',
            ),
        ),
    ]
