# Generated by Django 5.2 on 2025-04-30 02:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0008_sensorcamera_monitor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcamera',
            name='state_change_timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
