# Generated by Django 5.2 on 2025-04-30 04:07

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sensorcamera_state_change_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameralogs',
            name='image_processed',
            field=models.ImageField(default=None, storage=core.models.CameraImageProcessedStorage, upload_to=''),
            preserve_default=False,
        ),
    ]
