# Generated by Django 5.2 on 2025-05-01 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_cameralogs_image_processed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorcamera',
            name='flood_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sensorcamera',
            name='location',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sensorcamera',
            name='monitor_state',
            field=models.CharField(choices=[('Dangerous', 'Dangerous'), ('Caution', 'Caution'), ('Safe', 'Safe')], default='Safe'),
        ),
        migrations.AlterField(
            model_name='sensorcamera',
            name='threshold_depth',
            field=models.FloatField(default=1),
        ),
    ]
