# Generated by Django 5.2 on 2025-05-01 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_sensorcamera_flood_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cameralogs',
            name='person_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cameralogs',
            name='pet_count',
            field=models.IntegerField(default=0),
        ),
    ]
