# Generated by Django 5.2 on 2025-05-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_cameralogs_person_count_cameralogs_pet_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcamera',
            name='person_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensorcamera',
            name='pet_count',
            field=models.IntegerField(default=0),
        ),
    ]
