# Generated by Django 5.2 on 2025-05-03 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sensorcamera_person_count_sensorcamera_pet_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cameralogs',
            name='pet_count',
        ),
        migrations.RemoveField(
            model_name='sensorcamera',
            name='pet_count',
        ),
        migrations.AddField(
            model_name='cameralogs',
            name='cat_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cameralogs',
            name='dog_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensorcamera',
            name='cat_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sensorcamera',
            name='dog_count',
            field=models.IntegerField(default=0),
        ),
    ]
