# Generated by Django 5.2 on 2025-05-03 04:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_cameralogs_pet_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcamera',
            name='last_camera_report',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='sensorcamera',
            name='last_sensor_report',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
