# Generated by Django 5.2 on 2025-05-06 04:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0015_sensorcamera_last_camera_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorcamera',
            name='monitor_state',
            field=models.CharField(
                choices=[
                    ('Dangerous', 'Dangerous'),
                    ('Caution', 'Caution'),
                    ('Safe', 'Safe'),
                    ('Inactive', 'Inactive'),
                ],
                default='Safe',
            ),
        ),
    ]
