# Generated by Django 5.2 on 2025-05-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0016_alter_sensorcamera_monitor_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorcamera',
            name='monitor_state',
            field=models.CharField(
                choices=[
                    ('Dangerous', 'Dangerous'),
                    ('Caution', 'Caution'),
                    ('Safe', 'Safe'),
                    ('Unresponsive Sensor', 'Unresponsive Sensor'),
                    ('Unresponsive Camera', 'Unresponsive Camera'),
                    ('Both Unresponsive', 'Unresponsive Both'),
                ],
                default='Safe',
            ),
        ),
    ]
