# Generated by Django 5.2 on 2025-05-09 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_sensorcamera_monitor_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcamera',
            name='is_wet',
            field=models.BooleanField(default=False),
        ),
    ]
