# Generated by Django 5.2 on 2025-05-11 10:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0018_sensorcamera_is_wet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcamera',
            name='token',
            field=models.CharField(
                blank=True,
                default='88d10788786b81328f934cbded0dfabaf0d39097e907b8505eaa012bffd1edac',
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
    ]
