# Generated by Django 5.2 on 2025-05-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0019_sensorcamera_token_rescuercontacts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorcamera',
            name='last_camera_report',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='sensorcamera',
            name='last_sensor_report',
            field=models.DateTimeField(null=True),
        ),
    ]
