# Generated by Django 5.2 on 2025-05-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0019_sensorcamera_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorcamera',
            name='token',
            field=models.CharField(
                blank=True,
                default='a266fa78a591ef6020c1d0065bd2f1ebf246c3caf36f1c4feb30025134c44117',
                max_length=128,
                null=True,
                unique=True,
            ),
        ),
    ]
