# Generated by Django 5.2 on 2025-05-11 16:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0021_alter_sensorcamera_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensorcamera',
            name='token',
        ),
    ]
