# Generated by Django 5.2 on 2025-05-11 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0022_remove_sensorcamera_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorcamera',
            name='token',
            field=models.CharField(
                blank=True,
                default='5599c8821de2505203c89b55d49325c57b8d741e8f9cbfe2bbc94705bfdd927e',
                max_length=128,
                null=True,
            ),
        ),
    ]
