# Generated by Django 5.2 on 2025-05-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_sensorcamera_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorcamera',
            name='token',
            field=models.CharField(blank=True, default='69146fc8a51eb66d62aa07cae1d658efbade015b77772e926ff1dd3634a0753f', max_length=128, null=True, unique=True),
        ),
    ]
