# Generated by Django 5.2 on 2025-05-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0026_alter_sensorcamera_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensorcamera',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
    ]
