name: Code Quality Checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: main

jobs:
  build:
    name: Run checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Run linters
        run: make lint

      - name: Run formatters
        run: make format
